//==================================================
// This file contains the Excluded objects
// Generated By User: abdulrauf
// Format Version: 2
// Date: Tue Nov 24 14:53:00 2020
// ExclMode: default
//==================================================
CHECKSUM: "4092380887 522551161"
INSTANCE: tbench_top.DUT.apb_slave_instance
Toggle PADDR [31:3] "logic PADDR[31:0]"
Toggle config_address [31:3] "logic config_address[31:0]"
CHECKSUM: "4092380887 3971364424"
INSTANCE: tbench_top.DUT.apb_slave_instance
Condition 2 "3167777305" "(PSELx && PENABLE && PWRITE && (PADDR == 4)) 1 -1" (1 "0111")
Condition 2 "3167777305" "(PSELx && PENABLE && PWRITE && (PADDR == 4)) 1 -1" (2 "1011")
Condition 2 "3167777305" "(PSELx && PENABLE && PWRITE && (PADDR == 4)) 1 -1" (3 "1101")
Condition 3 "3099749638" "(PSELx && PENABLE && ((~PWRITE)) && (PADDR == 5)) 1 -1" (1 "0111")
Condition 3 "3099749638" "(PSELx && PENABLE && ((~PWRITE)) && (PADDR == 5)) 1 -1" (2 "1011")
Condition 3 "3099749638" "(PSELx && PENABLE && ((~PWRITE)) && (PADDR == 5)) 1 -1" (3 "1101")
Condition 4 "2483542420" "(PSELx && PENABLE && PWRITE && config_temp) 1 -1" (1 "0111")
Condition 4 "2483542420" "(PSELx && PENABLE && PWRITE && config_temp) 1 -1" (2 "1011")
Condition 5 "283479252" "(PSELx && PENABLE && ((~PWRITE)) && config_temp) 1 -1" (1 "0111")
CHECKSUM: "3629014953 664005823"
INSTANCE: tbench_top.DUT.apb_uart_instance.BRG_instance
Toggle tx_reg [0] "reg tx_reg[13:0]"
Toggle rx_reg [10] "reg rx_reg[10:0]"
CHECKSUM: "3913109507 1039338994"
INSTANCE: tbench_top.DUT.apb_uart_instance.receiver_instance
Block 7 "577919324" "n_state = IDLE;"
Block 26 "2684728402" "parity_check = 0;"
Block 38 "3396421125" "count_enable = 1;"
CHECKSUM: "3913109507 1154894806"
INSTANCE: tbench_top.DUT.apb_uart_instance.receiver_instance
Fsm p_state "1154894806"
Transition RX_DATA_BITS->IDLE "2->0"
Transition RX_PARITY->IDLE "3->0"
Transition RX_START_BIT->IDLE "1->0"
Transition RX_STOP_BIT1->IDLE "4->0"
CHECKSUM: "3913109507 3689054522"
INSTANCE: tbench_top.DUT.apb_uart_instance.receiver_instance
Condition 3 "2559278012" "((tick_count == 4'h7) && RX) 1 -1" (2 "10")
Condition 3 "2559278012" "((tick_count == 4'h7) && RX) 1 -1" (3 "11")
Condition 17 "3494317877" "((p_state == RX_DATA_BITS) && (tick_count == 4'hf) && (bit_count == (frame_length - 1)) && parity_enable) 1 -1" (1 "0111")
Condition 18 "1798615209" "((p_state == RX_DATA_BITS) && (tick_count == 4'hf) && (bit_count == (frame_length - 1)) && ((~parity_enable))) 1 -1" (1 "0111")
Condition 21 "3910074157" "((p_state == RX_STOP_BIT2) && (tick_count == 4'hf) && (index_count < 6'h20) && ((~RX))) 1 -1" (2 "1011")
Condition 22 "2780359193" "((p_state == RX_STOP_BIT2) && (tick_count == 4'hf) && (index_count >= (32 - 1))) 1 -1" (2 "101")
CHECKSUM: "3913109507 2589242209"
INSTANCE: tbench_top.DUT.apb_uart_instance.receiver_instance
Branch 1 "1376650604" "p_state" (3) "p_state RX_START_BIT ,-,0,1,-,-,-,-,-,-,-,-"
Branch 2 "2323120912" "p_state" (7) "p_state RX_PARITY ,-,-,default,-,-,-,-"
Branch 2 "2323120912" "p_state" (14) "p_state RX_STOP_BIT2 ,-,-,-,-,-,-,0"
CHECKSUM: "1384784785 3621196043"
INSTANCE: tbench_top.DUT.apb_uart_instance.transmtr_instance
Block 24 "3034295266" "for (n = 0; (n < 4); n += 1)"
Block 25 "3420801546" "parity_bit[n] <= (~^write_data[(n * 8)+:8]);"
CHECKSUM: "1384784785 1871916984"
INSTANCE: tbench_top.DUT.apb_uart_instance.transmtr_instance
Toggle TX_ERROR "logic TX_ERROR"
Toggle TX_DATA_REG [35:32] "logic TX_DATA_REG[35:0]"
Toggle start_bit "logic start_bit"
Toggle stop_bit "logic stop_bit"
CHECKSUM: "1384784785 1760036962"
INSTANCE: tbench_top.DUT.apb_uart_instance.transmtr_instance
Fsm current_state "1760036962"
Transition TX_DATA_BITS->IDLE "2->0"
Transition TX_FIRST_STOP_BIT->IDLE "4->0"
Transition TX_PARITY_BIT->IDLE "3->0"
Transition TX_SECOND_STOP_BIT->IDLE "5->0"
Transition TX_START_BIT->IDLE "1->0"
CHECKSUM: "1384784785 274464932"
INSTANCE: tbench_top.DUT.apb_uart_instance.transmtr_instance
Condition 1 "639994191" "((Tx_bit_count == (frame_length - 1)) && parity_enable) 1 -1" (1 "01")
Condition 2 "3583185078" "(((~stop_bits)) && (index_count < 6'h1f)) 1 -1" (1 "01")
CHECKSUM: "1384784785 1412985059"
INSTANCE: tbench_top.DUT.apb_uart_instance.transmtr_instance
Branch 0 "3636045486" "(frame_length == 4'd5)" (9) "(frame_length == 4'd5) 0,-,0,-,0,-,1,2'b10 "
CHECKSUM: "761582593 3642605761"
INSTANCE: tbench_top.DUT.apb_uart_instance
Toggle config_address [31:3] "logic config_address[31:0]"
Toggle config_error "logic config_error"
Toggle TX_ERROR "logic TX_ERROR"
Toggle PRDATA_config [31:17] "logic PRDATA_config[31:0]"
CHECKSUM: "761582593 1512133313"
INSTANCE: tbench_top.DUT.apb_uart_instance
Condition 10 "3646862415" "(config_error || TX_ERROR || RX_ERROR) 1 -1" (3 "010")
Condition 10 "3646862415" "(config_error || TX_ERROR || RX_ERROR) 1 -1" (4 "100")
CHECKSUM: "3165485516 4034193578"
INSTANCE: tbench_top.vifapb
Toggle PADDR [31:3] "logic PADDR[31:0]"
CHECKSUM: "1778299243 1493290169"
INSTANCE: tbench_top.DUT
Toggle PADDR [31:3] "logic PADDR[31:0]"
Toggle config_address_apb [31:3] "logic config_address_apb[31:0]"
CHECKSUM: "1384784785 3621196043"
INSTANCE: tbench_top.DUT.apb_uart_instance.transmtr_instance
Block 24 "3034295266" "for (n = 0; (n < 4); n += 1)"
Block 25 "3420801546" "parity_bit[n] <= (~^write_data[(n * 8)+:8]);"
Block 29 "255998375" "parity_bit <= 7'bxxxxxxx;"
CHECKSUM: "1384784785 1871916984"
INSTANCE: tbench_top.DUT.apb_uart_instance.transmtr_instance
Toggle TX_ERROR "logic TX_ERROR"
Toggle TX_DATA_REG [35:32] "logic TX_DATA_REG[35:0]"
Toggle start_bit "logic start_bit"
Toggle stop_bit "logic stop_bit"
CHECKSUM: "1384784785 1760036962"
INSTANCE: tbench_top.DUT.apb_uart_instance.transmtr_instance
Fsm current_state "1760036962"
Transition TX_DATA_BITS->IDLE "2->0"
Transition TX_FIRST_STOP_BIT->IDLE "4->0"
Transition TX_PARITY_BIT->IDLE "3->0"
Transition TX_SECOND_STOP_BIT->IDLE "5->0"
Transition TX_START_BIT->IDLE "1->0"
CHECKSUM: "1384784785 274464932"
INSTANCE: tbench_top.DUT.apb_uart_instance.transmtr_instance
Condition 1 "639994191" "((Tx_bit_count == (frame_length - 1)) && parity_enable) 1 -1" (1 "01")
Condition 2 "3583185078" "(((~stop_bits)) && (index_count < 6'h1f)) 1 -1" (1 "01")
CHECKSUM: "1384784785 1412985059"
INSTANCE: tbench_top.DUT.apb_uart_instance.transmtr_instance
Branch 0 "3636045486" "(frame_length == 4'd5)" (9) "(frame_length == 4'd5) 0,-,0,-,0,-,1,2'b10 "
Branch 0 "3636045486" "(frame_length == 4'd5)" (12) "(frame_length == 4'd5) 0,-,0,-,0,-,0,-"
CHECKSUM: "3913109507 1039338994"
INSTANCE: tbench_top.DUT.apb_uart_instance.receiver_instance
Block 7 "577919324" "n_state = IDLE;"
Block 26 "2684728402" "parity_check = 0;"
Block 38 "3396421125" "count_enable = 1;"
CHECKSUM: "3913109507 1154894806"
INSTANCE: tbench_top.DUT.apb_uart_instance.receiver_instance
Fsm p_state "1154894806"
Transition RX_DATA_BITS->IDLE "2->0"
Transition RX_PARITY->IDLE "3->0"
Transition RX_START_BIT->IDLE "1->0"
Transition RX_STOP_BIT1->IDLE "4->0"
CHECKSUM: "3913109507 3689054522"
INSTANCE: tbench_top.DUT.apb_uart_instance.receiver_instance
Condition 3 "2559278012" "((tick_count == 4'h7) && RX) 1 -1" (2 "10")
Condition 3 "2559278012" "((tick_count == 4'h7) && RX) 1 -1" (3 "11")
Condition 17 "3494317877" "((p_state == RX_DATA_BITS) && (tick_count == 4'hf) && (bit_count == (frame_length - 1)) && parity_enable) 1 -1" (1 "0111")
Condition 18 "1798615209" "((p_state == RX_DATA_BITS) && (tick_count == 4'hf) && (bit_count == (frame_length - 1)) && ((~parity_enable))) 1 -1" (1 "0111")
Condition 21 "3910074157" "((p_state == RX_STOP_BIT2) && (tick_count == 4'hf) && (index_count < 6'h20) && ((~RX))) 1 -1" (2 "1011")
Condition 22 "2780359193" "((p_state == RX_STOP_BIT2) && (tick_count == 4'hf) && (index_count >= (32 - 1))) 1 -1" (2 "101")
CHECKSUM: "3913109507 2589242209"
INSTANCE: tbench_top.DUT.apb_uart_instance.receiver_instance
Branch 1 "1376650604" "p_state" (3) "p_state RX_START_BIT ,-,0,1,-,-,-,-,-,-,-,-"
Branch 2 "2323120912" "p_state" (7) "p_state RX_PARITY ,-,-,default,-,-,-,-"
Branch 2 "2323120912" "p_state" (14) "p_state RX_STOP_BIT2 ,-,-,-,-,-,-,0"
CHECKSUM: "1778299243 1493290169"
INSTANCE: tbench_top.DUT
Toggle PADDR [31:3] "logic PADDR[31:0]"
Toggle config_address_apb [31:3] "logic config_address_apb[31:0]"
CHECKSUM: "1740898096 2010202410"
INSTANCE: tbench_top.vifapb
Toggle PADDR [31:3] "logic PADDR[31:0]"
CHECKSUM: "761582593 3642605761"
INSTANCE: tbench_top.DUT.apb_uart_instance
Toggle config_address [31:3] "logic config_address[31:0]"
Toggle config_error "logic config_error"
Toggle TX_ERROR "logic TX_ERROR"
Toggle PRDATA_config [31:17] "logic PRDATA_config[31:0]"
CHECKSUM: "761582593 1512133313"
INSTANCE: tbench_top.DUT.apb_uart_instance
Condition 10 "3646862415" "(config_error || TX_ERROR || RX_ERROR) 1 -1" (3 "010")
Condition 10 "3646862415" "(config_error || TX_ERROR || RX_ERROR) 1 -1" (4 "100")
CHECKSUM: "3629014953 664005823"
INSTANCE: tbench_top.DUT.apb_uart_instance.BRG_instance
Toggle tx_reg [0] "reg tx_reg[13:0]"
Toggle rx_reg [10] "reg rx_reg[10:0]"
CHECKSUM: "4092380887 522551161"
INSTANCE: tbench_top.DUT.apb_slave_instance
Toggle PADDR [31:3] "logic PADDR[31:0]"
Toggle config_address [31:3] "logic config_address[31:0]"
CHECKSUM: "4092380887 3971364424"
INSTANCE: tbench_top.DUT.apb_slave_instance
Condition 2 "3167777305" "(PSELx && PENABLE && PWRITE && (PADDR == 4)) 1 -1" (1 "0111")
Condition 2 "3167777305" "(PSELx && PENABLE && PWRITE && (PADDR == 4)) 1 -1" (2 "1011")
Condition 2 "3167777305" "(PSELx && PENABLE && PWRITE && (PADDR == 4)) 1 -1" (3 "1101")
Condition 3 "3099749638" "(PSELx && PENABLE && ((~PWRITE)) && (PADDR == 5)) 1 -1" (1 "0111")
Condition 3 "3099749638" "(PSELx && PENABLE && ((~PWRITE)) && (PADDR == 5)) 1 -1" (2 "1011")
Condition 3 "3099749638" "(PSELx && PENABLE && ((~PWRITE)) && (PADDR == 5)) 1 -1" (3 "1101")
Condition 4 "2483542420" "(PSELx && PENABLE && PWRITE && config_temp) 1 -1" (1 "0111")
Condition 4 "2483542420" "(PSELx && PENABLE && PWRITE && config_temp) 1 -1" (2 "1011")
Condition 5 "283479252" "(PSELx && PENABLE && ((~PWRITE)) && config_temp) 1 -1" (1 "0111")
CHECKSUM: "1264650322 1392056418"
INSTANCE: tbench_top.vifclk
Toggle first_reset_started "bit first_reset_started"
CHECKSUM: "1740898096 2010202410"
INSTANCE: tbench_top.vifapb
Toggle PADDR [31:3] "logic PADDR[31:0]"
CHECKSUM: "4092380887 522551161"
INSTANCE: tbench_top.DUT.apb_slave_instance
Toggle PADDR [31:3] "logic PADDR[31:0]"
Toggle config_address [31:3] "logic config_address[31:0]"
CHECKSUM: "4092380887 3971364424"
INSTANCE: tbench_top.DUT.apb_slave_instance
Condition 2 "3167777305" "(PSELx && PENABLE && PWRITE && (PADDR == 4)) 1 -1" (1 "0111")
Condition 2 "3167777305" "(PSELx && PENABLE && PWRITE && (PADDR == 4)) 1 -1" (2 "1011")
Condition 2 "3167777305" "(PSELx && PENABLE && PWRITE && (PADDR == 4)) 1 -1" (3 "1101")
Condition 3 "3099749638" "(PSELx && PENABLE && ((~PWRITE)) && (PADDR == 5)) 1 -1" (1 "0111")
Condition 3 "3099749638" "(PSELx && PENABLE && ((~PWRITE)) && (PADDR == 5)) 1 -1" (2 "1011")
Condition 3 "3099749638" "(PSELx && PENABLE && ((~PWRITE)) && (PADDR == 5)) 1 -1" (3 "1101")
Condition 4 "2483542420" "(PSELx && PENABLE && PWRITE && config_temp) 1 -1" (1 "0111")
Condition 4 "2483542420" "(PSELx && PENABLE && PWRITE && config_temp) 1 -1" (2 "1011")
Condition 5 "283479252" "(PSELx && PENABLE && ((~PWRITE)) && config_temp) 1 -1" (1 "0111")
CHECKSUM: "3913109507 1039338994"
INSTANCE: tbench_top.DUT.apb_uart_instance.receiver_instance
Block 7 "577919324" "n_state = IDLE;"
Block 26 "2684728402" "parity_check = 0;"
Block 38 "3396421125" "count_enable = 1;"
CHECKSUM: "3913109507 1154894806"
INSTANCE: tbench_top.DUT.apb_uart_instance.receiver_instance
Fsm p_state "1154894806"
Transition RX_DATA_BITS->IDLE "2->0"
Transition RX_PARITY->IDLE "3->0"
Transition RX_START_BIT->IDLE "1->0"
Transition RX_STOP_BIT1->IDLE "4->0"
CHECKSUM: "3913109507 3689054522"
INSTANCE: tbench_top.DUT.apb_uart_instance.receiver_instance
Condition 3 "2559278012" "((tick_count == 4'h7) && RX) 1 -1" (2 "10")
Condition 3 "2559278012" "((tick_count == 4'h7) && RX) 1 -1" (3 "11")
Condition 17 "3494317877" "((p_state == RX_DATA_BITS) && (tick_count == 4'hf) && (bit_count == (frame_length - 1)) && parity_enable) 1 -1" (1 "0111")
Condition 18 "1798615209" "((p_state == RX_DATA_BITS) && (tick_count == 4'hf) && (bit_count == (frame_length - 1)) && ((~parity_enable))) 1 -1" (1 "0111")
Condition 21 "3910074157" "((p_state == RX_STOP_BIT2) && (tick_count == 4'hf) && (index_count < 6'h20) && ((~RX))) 1 -1" (2 "1011")
Condition 22 "2780359193" "((p_state == RX_STOP_BIT2) && (tick_count == 4'hf) && (index_count >= (32 - 1))) 1 -1" (2 "101")
CHECKSUM: "3913109507 2589242209"
INSTANCE: tbench_top.DUT.apb_uart_instance.receiver_instance
Branch 1 "1376650604" "p_state" (3) "p_state RX_START_BIT ,-,0,1,-,-,-,-,-,-,-,-"
Branch 2 "2323120912" "p_state" (7) "p_state RX_PARITY ,-,-,default,-,-,-,-"
Branch 2 "2323120912" "p_state" (14) "p_state RX_STOP_BIT2 ,-,-,-,-,-,-,0"
CHECKSUM: "1384784785 3621196043"
INSTANCE: tbench_top.DUT.apb_uart_instance.transmtr_instance
Block 24 "3034295266" "for (n = 0; (n < 4); n += 1)"
Block 25 "3420801546" "parity_bit[n] <= (~^write_data[(n * 8)+:8]);"
Block 29 "255998375" "parity_bit <= 7'bxxxxxxx;"
CHECKSUM: "1384784785 1871916984"
INSTANCE: tbench_top.DUT.apb_uart_instance.transmtr_instance
Toggle TX_ERROR "logic TX_ERROR"
Toggle TX_DATA_REG [35:32] "logic TX_DATA_REG[35:0]"
Toggle start_bit "logic start_bit"
Toggle stop_bit "logic stop_bit"
CHECKSUM: "1384784785 1760036962"
INSTANCE: tbench_top.DUT.apb_uart_instance.transmtr_instance
Fsm current_state "1760036962"
Transition TX_DATA_BITS->IDLE "2->0"
Transition TX_FIRST_STOP_BIT->IDLE "4->0"
Transition TX_PARITY_BIT->IDLE "3->0"
Transition TX_SECOND_STOP_BIT->IDLE "5->0"
Transition TX_START_BIT->IDLE "1->0"
CHECKSUM: "1384784785 274464932"
INSTANCE: tbench_top.DUT.apb_uart_instance.transmtr_instance
Condition 1 "639994191" "((Tx_bit_count == (frame_length - 1)) && parity_enable) 1 -1" (1 "01")
Condition 2 "3583185078" "(((~stop_bits)) && (index_count < 6'h1f)) 1 -1" (1 "01")
CHECKSUM: "1384784785 1412985059"
INSTANCE: tbench_top.DUT.apb_uart_instance.transmtr_instance
Branch 0 "3636045486" "(frame_length == 4'd5)" (9) "(frame_length == 4'd5) 0,-,0,-,0,-,1,2'b10 "
Branch 0 "3636045486" "(frame_length == 4'd5)" (12) "(frame_length == 4'd5) 0,-,0,-,0,-,0,-"
CHECKSUM: "1264650322 1392056418"
INSTANCE: tbench_top.vifclk
Toggle first_reset_started "bit first_reset_started"
CHECKSUM: "3629014953 664005823"
INSTANCE: tbench_top.DUT.apb_uart_instance.BRG_instance
Toggle tx_reg [0] "reg tx_reg[13:0]"
Toggle rx_reg [10] "reg rx_reg[10:0]"
CHECKSUM: "761582593 3642605761"
INSTANCE: tbench_top.DUT.apb_uart_instance
Toggle config_address [31:3] "logic config_address[31:0]"
Toggle config_error "logic config_error"
Toggle TX_ERROR "logic TX_ERROR"
Toggle PRDATA_config [31:17] "logic PRDATA_config[31:0]"
CHECKSUM: "761582593 1512133313"
INSTANCE: tbench_top.DUT.apb_uart_instance
Condition 10 "3646862415" "(config_error || TX_ERROR || RX_ERROR) 1 -1" (3 "010")
Condition 10 "3646862415" "(config_error || TX_ERROR || RX_ERROR) 1 -1" (4 "100")
CHECKSUM: "1778299243 1493290169"
INSTANCE: tbench_top.DUT
Toggle PADDR [31:3] "logic PADDR[31:0]"
Toggle config_address_apb [31:3] "logic config_address_apb[31:0]"
